#! /bin/sh
#
# Example panel for lemonbar

. panel_colors

num_mon=$(bspc query -M | wc -l)
s="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG} | %{B-}%{F-}"

while read -r line ; do
	case $line in
		S*)
			# clock output
			sys="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
			sys="%{A:gsimplecal:}$sys%{A}"
			;;
		#K*)
		#	kernel="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG} ${line#?}%{B-}%{F-}"
		#	;;
		D*)
			dis="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
			;;
		M*)
			if [ "${line#?}" = "on" ]
			then
				volstat=1
			else
				volicon="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}%{B-}%{F-}"
				volstat=0
			fi
			;;
		V*)
			if [ "$volstat" = "1" ]
			then
				if ((0 <= ${line#?} && ${line#?} <= 40))
				then
					volicon="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}%{B-}%{F-}"
				elif ((41 <= ${line#?}))
				then
					volicon="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}%{B-}%{F-}"
				fi
			fi
			vollev="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
			;;
		C*)
			cpu="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%{B-}%{F-}"
			cpu="%{A:cpunotify & ramnotify & hddnotify:}$cpu%{A}"
			;;
		T*)
			if [ "${line#?}" -gt "75" ]
			then
				temp="%{F#ff0010}%{B$COLOR_SYS_BG} ${line#?}°C%{B-}%{F-}"
			else
				temp=""
			fi
			;;
		B*)
			case ${line#?} in
				[0])
					#bicon=""
					bstat=0
					;;
				[1])
					bicon="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}%{B-}%{F-}"
					bstat=1
					bicon="%{A:batnotify:}$bicon%{A}"
					;;
			esac
			;;

		b*)

			if [ "$bstat" = "0" ] 
			then
				if ((0 <= ${line#?} && ${line#?}<= 9))
				then
					bicon=""
					bicon="%{F#ff0010}%{B$COLOR_SYS_BG}$bicon%{B-}%F-}"
					bicon="%{A:batnotify:}$bicon%{A}"
				elif ((10 <= ${line#?} && ${line#?}<= 24))
				then
					bicon=""
					bicon="%{A:batnotify:}$bicon%{A}"
				elif ((25 <= ${line#?} && ${line#?}<= 49))
				then
					bicon=""
					bicon="%{A:batnotify:}$bicon%{A}"
				elif ((50 <= ${line#?} && ${line#?}<= 74))
				then
					bicon=""
					bicon="%{A:batnotify:}$bicon%{A}"
				elif ((75 <= ${line#?} && ${line#?}<= 90))
				then
					bicon=""
					bicon="%{A:batnotify:}$bicon%{A}"
				elif ((91 <= ${line#?} && ${line#?}<= 100))
				then
					bicon=""
					bicon="%{A:batnotify:}$bicon%{A}"
				fi
			fi
			if [ -f "/sys/class/power_supply/BAT0/present" ]
			then
				bperc="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}${line#?}%%{B-}%{F-}"
				bperc="%{A:batnotify:}$bperc%{A}"
			else
				bperc=""
			fi
			;;
		X*)
			# xtitle output
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
			;;
		W*)
			# bspwm's state
			wm=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						[ $num_mon -lt 2 ] && shift && continue
						case $item in
							m*)
								# monitor
								FG=$COLOR_MONITOR_FG
								BG=$COLOR_MONITOR_BG
								;;
							M*)
								# focused monitor
								FG=$COLOR_FOCUSED_MONITOR_FG
								BG=$COLOR_FOCUSED_MONITOR_BG
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					[fFoOuU]*)
						case $item in
							f*)
								# free desktop
								FG=$COLOR_FREE_FG
								BG=$COLOR_FREE_BG
								;;
							F*)
								# focused free desktop
								FG=$COLOR_FOCUSED_FREE_FG
								BG=$COLOR_FOCUSED_FREE_BG
								;;
							o*)
								# occupied desktop
								FG=$COLOR_OCCUPIED_FG
								BG=$COLOR_OCCUPIED_BG
								;;
							O*)
								# focused occupied desktop
								FG=$COLOR_FOCUSED_OCCUPIED_FG
								BG=$COLOR_FOCUSED_OCCUPIED_BG
								;;
							u*)
								# urgent desktop
								FG=$COLOR_URGENT_FG
								BG=$COLOR_URGENT_BG
								;;
							U*)
								# focused urgent desktop
								FG=$COLOR_FOCUSED_URGENT_FG
								BG=$COLOR_FOCUSED_URGENT_BG
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					[LTG]*)
						# layout, state and flags
						wm="${wm}%{F$COLOR_STATE_FG}%{B$COLOR_STATE_BG} ${name} %{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}${wm}%{c}${title}%{r}${cpu}${temp}${s}${volicon}${vollev}\
		${s}${dis}${s}${bicon}${bperc}${s}${sys}"
done
