#! /bin/sh

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

#PANEL_FONT1="Hack-10"
PANEL_FONT1="Source Sans Pro Semibold-10"
PANEL_FONT2="FontAwesome-11"

bspc config top_padding $PANEL_HEIGHT
bspc subscribe report > "$PANEL_FIFO" &
xtitle -sf 'X%s' > "$PANEL_FIFO" & # window title
clock -sf 'S%H:%M.%S' -i 1 > "$PANEL_FIFO" & # clock
mysysinfo -%C  -C -l5 > "$PANEL_FIFO" & # cpu usage
mysysinfo -%T  -T -l5 > "$PANEL_FIFO" & # temperature
mysysinfo -%B -B -l5 > "$PANEL_FIFO" & # ac adapter
mysysinfo -%b -b -l5 > "$PANEL_FIFO" & # battery percent
#echo "K$(uname -r)" > "$PANEL_FIFO" & # kernel

while true; do
	vol=$(amixer get Master | awk 'END{gsub(/\[|\]|%/,""); print $5}')
	volstat=$(amixer get Master | awk 'END{gsub(/\[|\]|%/,""); print $6}')
	echo "V${vol}" > "$PANEL_FIFO" &
	echo "M${volstat}" > "$PANEL_FIFO" &
	echo "D$(cat /sys/class/backlight/acpi_video0/actual_brightness)" > "$PANEL_FIFO" &
	sleep 0.25
done &


. panel_colors

panel_bar < "$PANEL_FIFO" | lemonbar -a 32 -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT -f "$PANEL_FONT1" -f "$PANEL_FONT2" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$PANEL_WM_NAME")
	tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
