#! /bin/sh

#vga1_samsung_right.sh

# set keyboard for x
exec setxkbmap -layout de &


# preselection color
bspc config presel_feedback_color "#1794D1" # arch logo color


# bspwm conffigs
bspc config top_padding 	12
bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
#bspc config history_aware_focus  true
bspc config click_to_focus 	 true

#ws1=
#ws2=
#ws3=
#ws4=4
#ws5=5
#ws6=6
#ws7=
#ws8=
#ws9=

ws1=1
ws2=2
ws3=3
ws4=4
ws5=5
ws6=6
ws7=7
ws8=8
ws9=9
ws10=10


# check wether a monitor is connected
xrandr -q | grep -v disconnected | grep -v LVDS1 | grep connected 
if [ $? -eq 0 ]; then
	# another monitor is connected
	multimon=0
	vga1_dell_left.sh
#	vga1_samsung_right.sh
else
	multimon=1
fi

# set multimon manually 1 to disable automatic monitor settings
#multimon=1
#vga1_disable.sh

if [ $multimon -eq 0 ];then
	bspc monitor VGA1 -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7
	bspc monitor LVDS1 -d $ws8 $ws9 $ws10
else
	bspc monitor -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7 $ws8 $ws9 $ws10
fi

#bspc monitor LVDS1 -d $ws1 $ws2 $ws3 $ws4 $ws5 
#bspc monitor VGA1 -d $ws6 $ws7 $ws8 $ws9 $ws10


# rules
bspc rule -a Gimp state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Lxappearance state=floating
bspc rule -a Google-chrome desktop=$ws2
bspc rule -a Steam desktop=$ws9
bspc rule -a Wine desktop=$ws9
bspc rule -a MPlayer state=floating
bspc rule -a Vlc state=floating follow=on
bspc rule -a TelegramDesktop desktop=$ws8 state=floating
#bspc rule -a VirtualBox desktop=^7 state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled


# applications and services to start
setbg &
compton -cb &
#panel &
launchpolybar &
dunst &
#tray &
autostart &
#sleep 1s &&
#nm-applet &
#insync start &
#Telegram &
