#!/bin/zsh

# waiting for internet connection etc
sleep 3

bspc rule -a Termite -o desktop=10 &&
	termite --exec=archaur &

sleep 0.5 &&

bspc rule -a Termite -o desktop=10 &&
	termite --exec=archupdates &

bspc rule -a qutebrowser -o desktop=10 &
archnews
