#!/bin/zsh

# waiting for internet connection etc
sleep 1

bspc rule -a Termite -o desktop=10 &&
	termite --exec=archaur &

sleep 0.5 &&

bspc rule -a Termite -o desktop=10 &&
	termite --exec=archupdates &

sleep 1 &&
bspc rule -a Surf -o desktop=10 &
archnews
