#!/bin/zsh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done


#detect monitors
if type "xrandr"; then
	for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
		MONITOR=$m polybar t420Top --config=/home/ismboe/.config/polybar/t420Top &
	done
else
	polybar t420Top --config=/home/ismboe/.config/polybar/t420Top &
fi
